version: "3"

services:
  postgres:
      image: postgres:14-alpine
      environment:
          POSTGRES_PASSWORD: pwakey
          POSTGRES_USER: pwauser
          POSTGRES_DB: pwa
      volumes:
          - ./data/pgdata:/var/lib/postgresql/data:delegated
      ports:
          - '5432:5432'

  backend:
    image: yiisoftware/yii2-php:8.1-apache
    environment:
          PASSWORD: pwakey
          USER: pwauser
          DB: pwa
          HOST: postgres
    volumes:
      - ./backend/composer/cache:/root/.composer/cache:delegated
      - ./backend/basic:/app:delegated
      
    ports:
      - '8000:80'